# -*- coding: utf-8 -*-
"""audio_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BaUyjFkbNUvIql_xg31ThDbi3Jc3C05f

# Audio Spoof Detection

Independent audio track: SEA-Spoof (Indonesian) + BioDeepAV audio combined, weighted sampling to balance source frequency, mel-spectrogram CNN

## 1. Environment setup
"""

# from google.colab import drive
# drive.mount('/content/drive')

import torch
print(f"CUDA available: {torch.cuda.is_available()}")


"""## Data loading — manifest + splits (audio)"""

import os
import pandas as pd

AUDIO_ROOT = "/content/drive/MyDrive/Video Spoof/data/audio/raw"

records = []
for source in os.listdir(AUDIO_ROOT):
    source_path = os.path.join(AUDIO_ROOT, source)
    if not os.path.isdir(source_path):
        continue
    for root, _, files in os.walk(source_path):
        for fname in files:
            if fname.endswith((".wav", ".flac")):
                full_path = os.path.join(root, fname)
                parts = full_path.split(os.sep)
                label = "real" if "real" in parts else "fake"
                records.append({"audio_path": full_path, "source": source, "label": label})

audio_manifest = pd.DataFrame(records)
print(f"Total audio files: {len(audio_manifest)}")
print(audio_manifest.groupby(["source", "label"]).size())

from sklearn.model_selection import train_test_split

audio_train_df, audio_val_df = train_test_split(
    audio_manifest, test_size=0.20,
    stratify=audio_manifest[["source", "label"]].apply(tuple, axis=1),
    random_state=42
)

print(f"Train: {len(audio_train_df)}, Val: {len(audio_val_df)}")

SPLITS_DIR = "/content/drive/MyDrive/Video Spoof/data/audio"
os.makedirs(SPLITS_DIR, exist_ok=True)
audio_train_df.to_csv(os.path.join(SPLITS_DIR, "split_train.csv"), index=False)
audio_val_df.to_csv(os.path.join(SPLITS_DIR, "split_val.csv"), index=False)

# Class weights (real/fake imbalance)
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

labels_numeric = audio_train_df["label"].map({"real": 0, "fake": 1}).values
audio_class_weights = compute_class_weight("balanced", classes=np.unique(labels_numeric), y=labels_numeric)
audio_class_weights_tensor = torch.tensor(audio_class_weights, dtype=torch.float32)
print(f"Class weights (real, fake): {audio_class_weights}")

# Weighted sampler — balances SEA-Spoof vs BioDeepAV draw frequency per epoch
from torch.utils.data import WeightedRandomSampler

source_counts = audio_train_df["source"].value_counts()
audio_train_df = audio_train_df.copy()
audio_train_df["sample_weight"] = audio_train_df["source"].map(lambda s: 1.0 / source_counts[s])

audio_sampler = WeightedRandomSampler(
    weights=audio_train_df["sample_weight"].values,
    num_samples=len(audio_train_df),
    replacement=True
)
print("Weighted sampler ready.")
print(source_counts)

"""## 7.c Feature extraction — mel-spectrogram, fixed-length clips"""

import librosa
import numpy as np

SAMPLE_RATE = 16000
CLIP_DURATION = 3.5          # seconds — pad/truncate every clip to this length
N_MELS = 128
CLIP_SAMPLES = int(SAMPLE_RATE * CLIP_DURATION)

def load_audio_fixed_length(path, sr=SAMPLE_RATE, target_samples=CLIP_SAMPLES):
    y, orig_sr = librosa.load(path, sr=sr)
    if len(y) > target_samples:
        start = np.random.randint(0, len(y) - target_samples + 1)
        y = y[start:start + target_samples]
    else:
        pad = target_samples - len(y)
        y = np.pad(y, (0, pad), mode="constant")
    return y

def audio_to_melspec(y, sr=SAMPLE_RATE, n_mels=N_MELS):
    mel = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=n_mels)
    mel_db = librosa.power_to_db(mel, ref=np.max)
    mel_db = (mel_db - mel_db.min()) / (mel_db.max() - mel_db.min() + 1e-8)
    return mel_db.astype(np.float32)

"""## 8. Dataset, DataLoader, model, training"""

from torch.utils.data import Dataset, DataLoader
import torch

class AudioSpoofDataset(Dataset):
    def __init__(self, df, augment=False):
        self.df = df.reset_index(drop=True)
        self.augment = augment
        self.label_map = {"real": 0, "fake": 1}

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        y = load_audio_fixed_length(row["audio_path"])

        if self.augment:
            if np.random.rand() < 0.3:
                y = y * np.random.uniform(0.7, 1.3)
            if np.random.rand() < 0.2:
                noise = np.random.normal(0, 0.005, y.shape).astype(np.float32)
                y = y + noise

        mel = audio_to_melspec(y)
        mel_tensor = torch.tensor(mel).unsqueeze(0)
        label = self.label_map[row["label"]]
        return mel_tensor, label

train_dataset = AudioSpoofDataset(audio_train_df, augment=True)
val_dataset = AudioSpoofDataset(audio_val_df, augment=False)

BATCH_SIZE = 32
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, sampler=audio_sampler, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

print(f"Train batches: {len(train_loader)}, Val batches: {len(val_loader)}")

sample_mel, sample_label = train_dataset[0]
print(f"Mel-spectrogram shape: {sample_mel.shape}")

# 8.b Baseline model — small CNN on mel-spectrograms
import torch.nn as nn

class AudioCNN(nn.Module):
    def __init__(self, num_classes=2):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, padding=1), nn.BatchNorm2d(32), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(32, 64, kernel_size=3, padding=1), nn.BatchNorm2d(64), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(64, 128, kernel_size=3, padding=1), nn.BatchNorm2d(128), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(128, 128, kernel_size=3, padding=1), nn.BatchNorm2d(128), nn.ReLU(),
            nn.AdaptiveAvgPool2d(1),
        )
        self.classifier = nn.Linear(128, num_classes)

    def forward(self, x):
        x = self.conv(x)
        x = x.flatten(1)
        return self.classifier(x)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
audio_model = AudioCNN().to(device)

total_params = sum(p.numel() for p in audio_model.parameters())
print(f"Total params: {total_params:,}")

# 8.c Training loop
criterion = nn.CrossEntropyLoss(weight=audio_class_weights_tensor.to(device))
optimizer = torch.optim.Adam(audio_model.parameters(), lr=1e-3)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="min", factor=0.5, patience=2)

def train_one_epoch_audio(model, loader, criterion, optimizer, device):
    model.train()
    running_loss, correct, total = 0.0, 0, 0
    for mels, labels in loader:
        mels, labels = mels.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(mels)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item() * mels.size(0)
        preds = outputs.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)
    return running_loss / total, correct / total

def validate_audio(model, loader, criterion, device):
    model.eval()
    running_loss, correct, total = 0.0, 0, 0
    with torch.no_grad():
        for mels, labels in loader:
            mels, labels = mels.to(device), labels.to(device)
            outputs = model(mels)
            loss = criterion(outputs, labels)
            running_loss += loss.item() * mels.size(0)
            preds = outputs.argmax(dim=1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)
    return running_loss / total, correct / total

import copy

CHECKPOINT_DIR = "/content/drive/MyDrive/Video Spoof/checkpoints/audio"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

EPOCHS = 15
EARLY_STOP_PATIENCE = 4
best_val_acc = 0.0
patience_counter = 0

for epoch in range(EPOCHS):
    train_loss, train_acc = train_one_epoch_audio(audio_model, train_loader, criterion, optimizer, device)
    val_loss, val_acc = validate_audio(audio_model, val_loader, criterion, device)
    scheduler.step(val_loss)

    print(f"Epoch {epoch+1}/{EPOCHS} | Train loss: {train_loss:.4f}, acc: {train_acc:.4f} | "
          f"Val loss: {val_loss:.4f}, acc: {val_acc:.4f}")

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(audio_model.state_dict(), os.path.join(CHECKPOINT_DIR, "best_audio_model.pt"))
        print(f"  New best saved (val_acc={val_acc:.4f})")
        patience_counter = 0
    else:
        patience_counter += 1
        if patience_counter >= EARLY_STOP_PATIENCE:
            print(f"Early stopping at epoch {epoch+1}")
            break

print(f"\nTraining complete. Best val accuracy: {best_val_acc:.4f}")

"""## Evaluation"""

from sklearn.metrics import accuracy_score, precision_recall_fscore_support, roc_auc_score, confusion_matrix
import numpy as np

audio_model.load_state_dict(torch.load(os.path.join(CHECKPOINT_DIR, "best_audio_model.pt")))
audio_model.eval()

def get_audio_predictions(model, loader, device):
    all_preds, all_probs, all_labels = [], [], []
    with torch.no_grad():
        for mels, labels in loader:
            mels = mels.to(device)
            outputs = model(mels)
            probs = torch.softmax(outputs, dim=1)[:, 1]
            preds = outputs.argmax(dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())
            all_labels.extend(labels.numpy())
    return np.array(all_labels), np.array(all_preds), np.array(all_probs)

val_labels, val_preds, val_probs = get_audio_predictions(audio_model, val_loader, device)

acc = accuracy_score(val_labels, val_preds)
prec, rec, f1, _ = precision_recall_fscore_support(val_labels, val_preds, average="binary")
auc = roc_auc_score(val_labels, val_probs)

print("=== Audio Val Evaluation ===")
print(f"Accuracy: {acc:.4f} | Precision: {prec:.4f} | Recall: {rec:.4f} | F1: {f1:.4f} | AUC: {auc:.4f}")
print(confusion_matrix(val_labels, val_preds))

# Per-source breakdown
audio_val_df_reset = audio_val_df.reset_index(drop=True)
audio_val_df_reset["pred"] = val_preds
audio_val_df_reset["correct"] = (audio_val_df_reset["label"].map({"real": 0, "fake": 1}) == val_preds)

print("Accuracy by source:")
print(audio_val_df_reset.groupby("source")["correct"].mean())

"""## Notes

- Model: small CNN on mel-spectrograms — lighter than Wav2Vec2
- Weighted sampler balances SEA-Spoof vs BioDeepAV draw frequency; augmentation (gain jitter, noise) adds variety especially for the smaller/more-often-redrawn source.
"""