# -*- coding: utf-8 -*-
"""video_spoof_train_v4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uhLaJ0xIqWMxJQ8gWsKOek5I8FCJuydJ

# Consecutive-Frame Re-Extraction for Temporal (CBAM+GRU) Model

Fix the frame continuity

## 1. Environment setup
"""

# from google.colab import drive
# drive.mount('/content/drive')

import torch
print(f"CUDA available: {torch.cuda.is_available()}")

# !pip install -q timm albumentations opencv-python-headless mediapipe scikit-learn pandas matplotlib

"""## 2. Consecutive-frame extraction from existing raw videos"""

N_CONSECUTIVE = 16

FRAMES_RAW_TEMPORAL = "/content/frames_raw_temporal"
os.makedirs(FRAMES_RAW_TEMPORAL, exist_ok=True)

import os, cv2


def extract_frames_consecutive(video_path, source, label, video_id, output_root,
                                  n_consecutive=N_CONSECUTIVE, start_offset_ratio=0.1):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        return 0

    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    if total_frames <= 0:
        cap.release()
        return 0

    start_frame = int(total_frames * start_offset_ratio)
    start_frame = min(start_frame, max(0, total_frames - n_consecutive))
    cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)

    dest_dir = os.path.join(output_root, source, label)
    os.makedirs(dest_dir, exist_ok=True)

    saved = 0
    frame_idx = start_frame
    while saved < n_consecutive:
        ret, frame = cap.read()
        if not ret:
            break
        fname = f"{video_id}_f{frame_idx}.jpg"
        cv2.imwrite(os.path.join(dest_dir, fname), frame)
        saved += 1
        frame_idx += 1

    cap.release()
    return saved

VIDEO_ROOT = "/content/drive/MyDrive/Video Spoof/data/video/raw"

FAKE_METHOD_NAMES = {"Deepfakes", "Face2Face", "FaceShifter", "FaceSwap",
                      "NeuralTextures", "DeepFakeDetection"}
REAL_SOURCE_NAMES = {"original"}  # top-level folder that IS the real class, not a container

def infer_source_and_label(root, video_root):
    rel_parts = os.path.relpath(root, video_root).split(os.sep)
    source = rel_parts[0]  # top-level folder = source dataset, always

    # Case 1: source folder itself IS the label (FF++ methods, "original")
    if source in FAKE_METHOD_NAMES:
        return source, "fake"
    if source in REAL_SOURCE_NAMES:
        return source, "real"

    # Case 2: source is a container with its own real/fake subfolders (DFDC, DeeperForensics, ...)
    for part in rel_parts[1:]:
        if part == "real":
            return source, "real"
        if part == "fake" or part in FAKE_METHOD_NAMES:
            return source, "fake"

    return source, None

video_list = []
skipped_unlabeled = []

for root, _, files in os.walk(VIDEO_ROOT):
    mp4_files = [f for f in files if f.endswith(".mp4")]
    if not mp4_files:
        continue

    source, label = infer_source_and_label(root, VIDEO_ROOT)
    if label is None:
        skipped_unlabeled.append(root)
        continue

    for fname in mp4_files:
        video_list.append({
            "path": os.path.join(root, fname),
            "source": source,
            "label": label,
            "video_id": os.path.splitext(fname)[0]
        })

print(f"Total videos found: {len(video_list)}")
print(f"Folders skipped (no label inferred): {len(skipped_unlabeled)}")
if skipped_unlabeled:
    print("Sample skipped paths:")
    for p in skipped_unlabeled[:10]:
        print(f"  {p}")

print(f"Total skipped: {len(skipped_unlabeled)}")
for p in skipped_unlabeled[:20]:
    print(p)

total_saved = 0
failed = 0
for i, v in enumerate(video_list):
    n = extract_frames_consecutive(v["path"], v["source"], v["label"], v["video_id"],
                                     FRAMES_RAW_TEMPORAL, n_consecutive=N_CONSECUTIVE)
    if n == 0:
        failed += 1
    total_saved += n
    if (i + 1) % 200 == 0:
        print(f"{i+1}/{len(video_list)} videos processed, {total_saved} frames saved, {failed} failed")

print(f"\nDone. Total consecutive frames extracted: {total_saved}")
print(f"Videos that failed to extract: {failed}")

BIO_VIDEO_ROOT = "/content/drive/MyDrive/Video Spoof/data/video/raw/BioDeepAV"

bio_video_list = []
for label in ["real", "fake"]:
    label_dir = os.path.join(BIO_VIDEO_ROOT, label)
    for fname in os.listdir(label_dir):
        if fname.endswith(".mp4"):
            bio_video_list.append({
                "path": os.path.join(label_dir, fname),
                "source": "BioDeepAV",
                "label": label,
                "video_id": os.path.splitext(fname)[0]
            })

print(f"BioDeepAV videos found: {len(bio_video_list)}")

total_saved, failed = 0, 0
for i, v in enumerate(bio_video_list):
    n = extract_frames_consecutive(v["path"], v["source"], v["label"], v["video_id"],
                                     FRAMES_RAW_TEMPORAL, n_consecutive=N_CONSECUTIVE)
    if n == 0:
        failed += 1
    total_saved += n
    if (i + 1) % 200 == 0:
        print(f"{i+1}/{len(bio_video_list)} videos processed, {total_saved} frames saved, {failed} failed")

print(f"\nDone. BioDeepAV consecutive frames extracted: {total_saved}, failed: {failed}")

import shutil

# Arguments: (target_zip_name, 'format', source_folder_path)
shutil.make_archive('frames_raw_temporal', 'zip', '/content/frames_raw_temporal')

# save to drive
DRIVE_DEST = "/content/drive/MyDrive/Video Spoof/data/video/frames_raw_temporal.zip"
shutil.copy('/content/frames_raw_temporal.zip', DRIVE_DEST)

size_mb = os.path.getsize(DRIVE_DEST) / (1024 * 1024)
print(f"Saved to Drive: {DRIVE_DEST} ({size_mb:.1f} MB)")

"""## 3. Face detection and cropping (MediaPipe) on the consecutive frames"""

# !wget -q -O /content/blaze_face_short_range.tflite \
#   https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/1/blaze_face_short_range.tflite

import mediapipe as mp
from mediapipe.tasks import python as mp_python
from mediapipe.tasks.python import vision

base_options = mp_python.BaseOptions(model_asset_path="/content/blaze_face_short_range.tflite")
options = vision.FaceDetectorOptions(base_options=base_options, min_detection_confidence=0.5)
detector = vision.FaceDetector.create_from_options(options)

def detect_and_crop_face(image_path, margin=0.2, output_size=224):
    img = cv2.imread(image_path)
    if img is None:
        return None
    h, w = img.shape[:2]
    rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb)
    result = detector.detect(mp_image)
    if not result.detections:
        return None
    best = max(result.detections, key=lambda d: d.categories[0].score)
    bbox = best.bounding_box
    x1 = max(0, int(bbox.origin_x - bbox.width * margin))
    y1 = max(0, int(bbox.origin_y - bbox.height * margin))
    x2 = min(w, int(bbox.origin_x + bbox.width * (1 + margin)))
    y2 = min(h, int(bbox.origin_y + bbox.height * (1 + margin)))
    cropped = img[y1:y2, x1:x2]
    if cropped.size == 0:
        return None
    return cv2.resize(cropped, (output_size, output_size))

FRAMES_PROCESSED_TEMPORAL = "/content/frames_processed_temporal"

processed_count, filled_count, skipped_videos = 0, 0, 0

for video_key, group in __import__("itertools").groupby(
        sorted(
            [(root, f) for root, _, files in os.walk(FRAMES_RAW_TEMPORAL) for f in files if f.endswith(".jpg")],
            key=lambda rf: rf[1]
        ),
        key=lambda rf: rf[1].split("_f")[0]
    ):
    pass  # placeholder — replaced by explicit per-video loop below for clarity

def extract_video_id_and_frame(fname):
    match = re.match(r"^(.*)_f(\d+)\.jpg$", fname)
    if not match:
        return None, None
    return match.group(1), int(match.group(2))

import re

# Build per-video frame lists first
video_frames = {}
for root, _, files in os.walk(FRAMES_RAW_TEMPORAL):
    for fname in files:
        if not fname.endswith(".jpg"):
            continue
        vid, fidx = extract_video_id_and_frame(fname)
        if vid is None:
            continue
        parts = root.split(os.sep)
        label, source = parts[-1], parts[-2]
        key = (source, label, vid)
        video_frames.setdefault(key, []).append((fidx, os.path.join(root, fname)))

print(f"Total videos found: {len(video_frames)}")

# for all video (other than BiodeepAV)
processed_count, filled_count, empty_videos = 0, 0, 0

for (source, label, vid), frame_list in video_frames.items():
    frame_list.sort(key=lambda x: x[0])
    dest_dir = os.path.join(FRAMES_PROCESSED_TEMPORAL, source, label)
    os.makedirs(dest_dir, exist_ok=True)

    last_valid_crop = None
    any_valid = False

    for fidx, src_path in frame_list:
        cropped = detect_and_crop_face(src_path)
        if cropped is not None:
            last_valid_crop = cropped
            any_valid = True
            processed_count += 1
        elif last_valid_crop is not None:
            # fill gap with the last valid crop, preserving sequence continuity
            cropped = last_valid_crop
            filled_count += 1
        else:
            continue  # no valid crop yet to fall back on — skip until first face is found

        fname = f"{vid}_f{fidx}.jpg"
        cv2.imwrite(os.path.join(dest_dir, fname), cropped)

    if not any_valid:
        empty_videos += 1

print(f"Cropped directly: {processed_count}")
print(f"Filled via nearest-valid-frame: {filled_count}")
print(f"Videos with NO detectable face at all (excluded): {empty_videos}")

bio_raw_dir = os.path.join(FRAMES_RAW_TEMPORAL, "BioDeepAV")

# Rebuild per-video frame lists for BioDeepAV specifically
bio_video_frames = {}
for root, _, files in os.walk(bio_raw_dir):
    for fname in files:
        if not fname.endswith(".jpg"):
            continue
        vid, fidx = extract_video_id_and_frame(fname)
        if vid is None:
            continue
        parts = root.split(os.sep)
        label = parts[-1]  # 'real' or 'fake'
        source = parts[-2]  # 'BioDeepAV'
        key = (source, label, vid)
        bio_video_frames.setdefault(key, []).append((fidx, os.path.join(root, fname)))

print(f"BioDeepAV videos to crop: {len(bio_video_frames)}")

# Confirm BioDeepAV frames
FRAMES_RAW_TEMPORAL = "/content/frames_raw_temporal"

raw_bio_count = sum(1 for root, _, files in os.walk(os.path.join(FRAMES_RAW_TEMPORAL, "BioDeepAV"))
                     for f in files if f.endswith(".jpg"))
processed_bio_count = sum(1 for root, _, files in os.walk(os.path.join(FRAMES_PROCESSED_TEMPORAL, "BioDeepAV"))
                           for f in files if f.endswith(".jpg"))

print(f"BioDeepAV raw frames: {raw_bio_count}")
print(f"BioDeepAV processed (cropped) frames: {processed_bio_count}")

# for BioDeepAV
processed_count, filled_count, empty_videos = 0, 0, 0

for (source, label, vid), frame_list in bio_video_frames.items():
    frame_list.sort(key=lambda x: x[0])
    dest_dir = os.path.join(FRAMES_PROCESSED_TEMPORAL, source, label)
    os.makedirs(dest_dir, exist_ok=True)

    last_valid_crop = None
    any_valid = False

    for fidx, src_path in frame_list:
        cropped = detect_and_crop_face(src_path)
        if cropped is not None:
            last_valid_crop = cropped
            any_valid = True
            processed_count += 1
        elif last_valid_crop is not None:
            cropped = last_valid_crop
            filled_count += 1
        else:
            continue

        fname = f"{vid}_f{fidx}.jpg"
        cv2.imwrite(os.path.join(dest_dir, fname), cropped)

    if not any_valid:
        empty_videos += 1

print(f"Cropped directly: {processed_count}")
print(f"Filled via nearest-valid-frame: {filled_count}")
print(f"Videos with no detectable face: {empty_videos}")

# Zip and save to Drive
# !zip -r -q /content/frames_processed_temporal.zip /content/frames_processed_temporal
# !cp /content/frames_processed_temporal.zip "/content/drive/MyDrive/Video Spoof/data/video/frames_processed_temporal.zip"

size_mb = os.path.getsize("/content/drive/MyDrive/Video Spoof/data/video/frames_processed_temporal.zip") / (1024*1024)
print(f"Saved to Drive ({size_mb:.1f} MB)")

"""## 4. Manifest + splits (temporal dataset)"""

import pandas as pd

records = []
for root, _, files in os.walk(FRAMES_PROCESSED_TEMPORAL):
    for fname in files:
        if fname.endswith(".jpg"):
            full_path = os.path.join(root, fname)
            parts = full_path.split(os.sep)
            label, source = parts[-2], parts[-3]
            records.append({"image_path": full_path, "source_dataset": source, "label": label})

temporal_manifest = pd.DataFrame(records)
print(f"Total frames: {len(temporal_manifest)}")
print(temporal_manifest.groupby(["source_dataset", "label"]).size())

print(temporal_manifest["source_dataset"].value_counts())

from sklearn.model_selection import train_test_split

bio_data = temporal_manifest[temporal_manifest["source_dataset"] == "BioDeepAV"]
other_data = temporal_manifest[temporal_manifest["source_dataset"] != "BioDeepAV"]

bio_trainval, bio_test = train_test_split(bio_data, test_size=0.4, stratify=bio_data["label"], random_state=42)
train_val_pool = pd.concat([other_data, bio_trainval], ignore_index=True)
final_test_set = bio_test.copy()

train_df, val_df = train_test_split(
    train_val_pool, test_size=0.20,
    stratify=train_val_pool[["source_dataset", "label"]].apply(tuple, axis=1),
    random_state=42
)

print(f"Train: {len(train_df)}, Val: {len(val_df)}, Test: {len(final_test_set)}")

SPLITS_DIR = "/content/drive/MyDrive/Video Spoof/data/video"
train_df.to_csv(os.path.join(SPLITS_DIR, "split_train_temporal.csv"), index=False)
val_df.to_csv(os.path.join(SPLITS_DIR, "split_val_temporal.csv"), index=False)
final_test_set.to_csv(os.path.join(SPLITS_DIR, "split_test_heldout_temporal.csv"), index=False)

"""## 5. CBAM + GRU model, sequence dataset (consecutive-aware), training

Loading
"""

# Unzip the already-processed frames
DRIVE_ZIP = "/content/drive/MyDrive/Video Spoof/data/video/frames_processed_temporal.zip"
# !unzip -o -q "{DRIVE_ZIP}" -d /content/

# Confirm extraction path

# Reload the splits already saved to Drive
import pandas as pd
import os

SPLITS_DIR = "/content/drive/MyDrive/Video Spoof/data/video"
train_df = pd.read_csv(os.path.join(SPLITS_DIR, "split_train_temporal.csv"))
val_df = pd.read_csv(os.path.join(SPLITS_DIR, "split_val_temporal.csv"))
final_test_set = pd.read_csv(os.path.join(SPLITS_DIR, "split_test_heldout_temporal.csv"))

print(f"Train: {len(train_df)}, Val: {len(val_df)}, Test: {len(final_test_set)}")
print(f"Sample path exists: {os.path.exists(train_df['image_path'].iloc[0])}")

import torch.nn as nn
import timm

class ChannelAttention(nn.Module):
    def __init__(self, channels, reduction=16):
        super().__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
        self.mlp = nn.Sequential(
            nn.Conv2d(channels, channels // reduction, 1, bias=False), nn.ReLU(),
            nn.Conv2d(channels // reduction, channels, 1, bias=False),
        )
        self.sigmoid = nn.Sigmoid()
    def forward(self, x):
        return self.sigmoid(self.mlp(self.avg_pool(x)) + self.mlp(self.max_pool(x)))

class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=7):
        super().__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size, padding=kernel_size // 2, bias=False)
        self.sigmoid = nn.Sigmoid()
    def forward(self, x):
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        return self.sigmoid(self.conv(torch.cat([avg_out, max_out], dim=1)))

class CBAM(nn.Module):
    def __init__(self, channels, reduction=16, kernel_size=7):
        super().__init__()
        self.channel_att = ChannelAttention(channels, reduction)
        self.spatial_att = SpatialAttention(kernel_size)
    def forward(self, x):
        x = x * self.channel_att(x)
        x = x * self.spatial_att(x)
        return x

class CBAM_GRU_DeepfakeDetector(nn.Module):
    def __init__(self, backbone_checkpoint=None, feature_dim=1280, gru_hidden=256, num_classes=2):
        super().__init__()
        self.backbone = timm.create_model("efficientnet_b0", pretrained=(backbone_checkpoint is None),
                                           num_classes=0, global_pool="")
        if backbone_checkpoint is not None:
            state_dict = torch.load(backbone_checkpoint, map_location="cpu")
            filtered = {k: v for k, v in state_dict.items() if not k.startswith("classifier")}
            self.backbone.load_state_dict(filtered, strict=False)
        self.cbam = CBAM(channels=feature_dim)
        self.pool = nn.AdaptiveAvgPool2d(1)
        self.gru = nn.GRU(feature_dim, gru_hidden, batch_first=True, bidirectional=True)
        self.classifier = nn.Linear(gru_hidden * 2, num_classes)

    def forward(self, x, lengths):
        B, T, C, H, W = x.shape
        x = x.view(B * T, C, H, W)
        feat_map = self.backbone.forward_features(x)
        feat_map = self.cbam(feat_map)
        feat_vec = self.pool(feat_map).flatten(1).view(B, T, -1)
        packed = nn.utils.rnn.pack_padded_sequence(feat_vec, lengths.cpu(), batch_first=True, enforce_sorted=False)
        _, h_n = self.gru(packed)
        h_cat = torch.cat([h_n[-2], h_n[-1]], dim=1)
        return self.classifier(h_cat)

from torch.utils.data import Dataset, DataLoader
from PIL import Image
import albumentations as A
from albumentations.pytorch import ToTensorV2
import numpy as np

IMG_SIZE = 224
seq_transform = A.Compose([
    A.Resize(IMG_SIZE, IMG_SIZE),
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.3),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2(),
])
val_seq_transform = A.Compose([
    A.Resize(IMG_SIZE, IMG_SIZE),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2(),
])

class VideoSequenceDataset(Dataset):
    def __init__(self, manifest_df, transform, max_seq_len=15):
        df = manifest_df.copy()
        parsed = df["image_path"].apply(lambda p: extract_video_id_and_frame(os.path.basename(p)))
        df["video_id"] = parsed.apply(lambda x: x[0])
        df["frame_idx"] = parsed.apply(lambda x: x[1])
        df = df.dropna(subset=["video_id", "frame_idx"])
        self.groups = df.sort_values("frame_idx").groupby("video_id")
        self.video_ids = list(self.groups.groups.keys())
        self.transform = transform
        self.max_seq_len = max_seq_len
        self.label_map = {"real": 0, "fake": 1}

    def __len__(self):
        return len(self.video_ids)

    def __getitem__(self, idx):
        vid = self.video_ids[idx]
        rows = self.groups.get_group(vid).head(self.max_seq_len)
        frames = []
        for _, row in rows.iterrows():
            img = np.array(Image.open(row["image_path"]).convert("RGB"))
            img = self.transform(image=img)["image"]
            frames.append(img)
        seq = torch.stack(frames)
        label = self.label_map[rows.iloc[0]["label"]]
        return seq, seq.shape[0], label

def collate_sequences(batch):
    seqs, lengths, labels = zip(*batch)
    max_len = max(lengths)
    padded = torch.zeros(len(seqs), max_len, *seqs[0].shape[1:])
    for i, s in enumerate(seqs):
        padded[i, :s.shape[0]] = s
    return padded, torch.tensor(lengths), torch.tensor(labels)

train_seq_ds = VideoSequenceDataset(train_df, seq_transform, max_seq_len=N_CONSECUTIVE)
val_seq_ds = VideoSequenceDataset(val_df, val_seq_transform, max_seq_len=N_CONSECUTIVE)
test_seq_ds = VideoSequenceDataset(final_test_set, val_seq_transform, max_seq_len=N_CONSECUTIVE)

BATCH_SIZE = 6
train_seq_loader = DataLoader(train_seq_ds, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_sequences, num_workers=2)
val_seq_loader = DataLoader(val_seq_ds, batch_size=BATCH_SIZE, shuffle=False, collate_fn=collate_sequences, num_workers=2)
test_seq_loader = DataLoader(test_seq_ds, batch_size=BATCH_SIZE, shuffle=False, collate_fn=collate_sequences, num_workers=2)

print(f"Train videos: {len(train_seq_ds)}, Val: {len(val_seq_ds)}, Test: {len(test_seq_ds)}")

from sklearn.utils.class_weight import compute_class_weight
import torch
import os

video_level_labels = [train_seq_ds.label_map[train_seq_ds.groups.get_group(vid)["label"].iloc[0]]
                       for vid in train_seq_ds.video_ids]
class_weights = compute_class_weight("balanced", classes=np.unique(video_level_labels), y=video_level_labels)
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float32)
print(f"Class weights: {class_weights}")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
CHECKPOINT_DIR = "/content/drive/MyDrive/Video Spoof/checkpoints/video"
existing_ckpt = os.path.join(CHECKPOINT_DIR, "best_model_v2.pt")

model = CBAM_GRU_DeepfakeDetector(
    backbone_checkpoint=existing_ckpt if os.path.exists(existing_ckpt) else None
).to(device)
print("Model ready.")

criterion = nn.CrossEntropyLoss(weight=class_weights_tensor.to(device))
optimizer = torch.optim.Adam(model.parameters(), lr=5e-5)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="min", factor=0.5, patience=2)

def train_one_epoch_seq(model, loader, criterion, optimizer, device):
    model.train()
    running_loss, correct, total = 0.0, 0, 0
    for seqs, lengths, labels in loader:
        seqs, labels = seqs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(seqs, lengths)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item() * seqs.size(0)
        correct += (outputs.argmax(1) == labels).sum().item()
        total += labels.size(0)
    return running_loss / total, correct / total

def validate_seq(model, loader, criterion, device):
    model.eval()
    running_loss, correct, total = 0.0, 0, 0
    with torch.no_grad():
        for seqs, lengths, labels in loader:
            seqs, labels = seqs.to(device), labels.to(device)
            outputs = model(seqs, lengths)
            loss = criterion(outputs, labels)
            running_loss += loss.item() * seqs.size(0)
            correct += (outputs.argmax(1) == labels).sum().item()
            total += labels.size(0)
    return running_loss / total, correct / total

TEMPORAL_CHECKPOINT_DIR = "/content/drive/MyDrive/Video Spoof/checkpoints/video_temporal_v2"
os.makedirs(TEMPORAL_CHECKPOINT_DIR, exist_ok=True)

EPOCHS = 15
EARLY_STOP_PATIENCE = 4
best_val_acc = 0.0
patience_counter = 0
history = {"train_loss": [], "train_acc": [], "val_loss": [], "val_acc": []}

for epoch in range(EPOCHS):
    train_loss, train_acc = train_one_epoch_seq(model, train_seq_loader, criterion, optimizer, device)
    val_loss, val_acc = validate_seq(model, val_seq_loader, criterion, device)
    scheduler.step(val_loss)

    history["train_loss"].append(train_loss); history["train_acc"].append(train_acc)
    history["val_loss"].append(val_loss); history["val_acc"].append(val_acc)

    print(f"Epoch {epoch+1}/{EPOCHS} | Train loss: {train_loss:.4f}, acc: {train_acc:.4f} | "
          f"Val loss: {val_loss:.4f}, acc: {val_acc:.4f}")

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), os.path.join(TEMPORAL_CHECKPOINT_DIR, "best_cbam_gru_consecutive.pt"))
        print(f"  New best saved (val_acc={val_acc:.4f})")
        patience_counter = 0
    else:
        patience_counter += 1
        if patience_counter >= EARLY_STOP_PATIENCE:
            print(f"Early stopping at epoch {epoch+1}")
            break

print(f"\nBest val accuracy: {best_val_acc:.4f}")

import json
with open(os.path.join(TEMPORAL_CHECKPOINT_DIR, "training_history.json"), "w") as f:
    json.dump(history, f)

"""## 6. Training curves + evaluation"""

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
epochs_range = range(1, len(history["train_loss"]) + 1)

axes[0].plot(epochs_range, history["train_loss"], label="Train Loss", marker="o")
axes[0].plot(epochs_range, history["val_loss"], label="Val Loss", marker="o")
axes[0].set_xlabel("Epoch"); axes[0].set_ylabel("Loss"); axes[0].set_title("Loss")
axes[0].legend(); axes[0].grid(alpha=0.3)

axes[1].plot(epochs_range, history["train_acc"], label="Train Acc", marker="o")
axes[1].plot(epochs_range, history["val_acc"], label="Val Acc", marker="o")
axes[1].set_xlabel("Epoch"); axes[1].set_ylabel("Accuracy"); axes[1].set_title("Accuracy")
axes[1].legend(); axes[1].grid(alpha=0.3)

plt.tight_layout()
fig_path = os.path.join(TEMPORAL_CHECKPOINT_DIR, "training_curves.png")
plt.savefig(fig_path, dpi=150, bbox_inches="tight")
print(f"Saved: {fig_path}")
plt.show()

from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix
import numpy as np

model.load_state_dict(torch.load(os.path.join(TEMPORAL_CHECKPOINT_DIR, "best_cbam_gru_consecutive.pt")))
model.eval()

def get_seq_predictions(model, loader, device):
    all_preds, all_probs, all_labels = [], [], []
    with torch.no_grad():
        for seqs, lengths, labels in loader:
            seqs = seqs.to(device)
            outputs = model(seqs, lengths)
            probs = torch.softmax(outputs, dim=1)[:, 1]
            all_preds.extend(outputs.argmax(1).cpu().numpy())
            all_probs.extend(probs.cpu().numpy())
            all_labels.extend(labels.numpy())
    return np.array(all_labels), np.array(all_preds), np.array(all_probs)

val_labels, val_preds, val_probs = get_seq_predictions(model, val_seq_loader, device)
print(f"Val — Acc: {accuracy_score(val_labels, val_preds):.4f}, AUC: {roc_auc_score(val_labels, val_probs):.4f}")
print(confusion_matrix(val_labels, val_preds))

test_labels, test_preds, test_probs = get_seq_predictions(model, test_seq_loader, device)
print(f"\nTest (BioDeepAV) — Acc: {accuracy_score(test_labels, test_preds):.4f}, AUC: {roc_auc_score(test_labels, test_probs):.4f}")
print(confusion_matrix(test_labels, test_preds))

"""## 7. Celeb DF V2 Testing (Other source)"""

# 1. List files first
import subprocess

def get_all_kaggle_files(dataset, page_size=200):
    all_lines, page_token, seen = [], None, set()
    while True:
        cmd = ["kaggle", "datasets", "files", dataset, "--csv", "--page-size", str(page_size)]
        if page_token:
            cmd += ["--page-token", page_token]
        result = subprocess.run(cmd, capture_output=True, text=True)
        lines = result.stdout.strip().split("\n")
        token_line = next((l for l in lines if l.startswith("Next Page Token")), None)
        data_lines = [l for l in lines if l.strip() and not l.startswith("Next Page Token") and l != "name"]
        all_lines.extend(data_lines)
        new_token = token_line.split("=")[-1].strip() if token_line else None
        if not new_token or new_token in seen:
            break
        seen.add(new_token)
        page_token = new_token
    return all_lines

celeb_files_raw = get_all_kaggle_files("reubensuju/celeb-df-v2")
celeb_files = [l.split(",")[0] for l in celeb_files_raw]
print(f"Total files: {len(celeb_files)}")
print(celeb_files[:5])

# 2. Filter by folder, sample a small set
def files_in_folder(files, folder_name):
    return [f for f in files if folder_name in f and f.endswith(".mp4")]

real_celeb = files_in_folder(celeb_files, "Celeb-real")
real_youtube = files_in_folder(celeb_files, "YouTube-real")
fake_synth = files_in_folder(celeb_files, "Celeb-synthesis")

print(f"Celeb-real: {len(real_celeb)}, YouTube-real: {len(real_youtube)}, Celeb-synthesis: {len(fake_synth)}")

# 3. Small balanced sample
import random
random.seed(42)

N_REAL = 75
N_FAKE = 75

all_real = real_celeb + real_youtube
sampled_real = random.sample(all_real, min(N_REAL, len(all_real)))
sampled_fake = random.sample(fake_synth, min(N_FAKE, len(fake_synth)))

print(f"Sampling {len(sampled_real)} real, {len(sampled_fake)} fake")

# 4. Download only the sampled files
import os

CELEB_DEST_REAL = "/content/celeb_df_test/real"
CELEB_DEST_FAKE = "/content/celeb_df_test/fake"
os.makedirs(CELEB_DEST_REAL, exist_ok=True)
os.makedirs(CELEB_DEST_FAKE, exist_ok=True)

def download_kaggle_file(dataset, file_path, dest_dir):
    fname = os.path.basename(file_path)
    if os.path.exists(os.path.join(dest_dir, fname)):
        return
    subprocess.run(["kaggle", "datasets", "download", dataset, "-f", file_path, "-p", dest_dir, "--force"], check=True)
    zip_path = os.path.join(dest_dir, fname + ".zip")
    if os.path.exists(zip_path):
        subprocess.run(["unzip", "-o", "-q", zip_path, "-d", dest_dir], check=True)
        os.remove(zip_path)

for i, f in enumerate(sampled_real):
    download_kaggle_file("reubensuju/celeb-df-v2", f, CELEB_DEST_REAL)
    if (i + 1) % 25 == 0:
        print(f"Real: {i+1}/{len(sampled_real)}")

for i, f in enumerate(sampled_fake):
    download_kaggle_file("reubensuju/celeb-df-v2", f, CELEB_DEST_FAKE)
    if (i + 1) % 25 == 0:
        print(f"Fake: {i+1}/{len(sampled_fake)}")

print("Celeb-DF sample download complete.")

# 5. Extract CONSECUTIVE frames
celeb_video_list = []
for label, folder in [("real", CELEB_DEST_REAL), ("fake", CELEB_DEST_FAKE)]:
    for fname in os.listdir(folder):
        if fname.endswith(".mp4"):
            celeb_video_list.append({
                "path": os.path.join(folder, fname),
                "label": label,
                "video_id": os.path.splitext(fname)[0]
            })

print(f"Videos to process: {len(celeb_video_list)}")

CELEB_FRAMES_RAW = "/content/celeb_df_frames_raw"
for v in celeb_video_list:
    extract_frames_consecutive(v["path"], "CelebDF", v["label"], v["video_id"],
                                 CELEB_FRAMES_RAW, n_consecutive=N_CONSECUTIVE)

print("Frame extraction done.")

# 6. Face crop with gap-filling
celeb_video_frames = {}
for root, _, files in os.walk(CELEB_FRAMES_RAW):
    for fname in files:
        if not fname.endswith(".jpg"):
            continue
        vid, fidx = extract_video_id_and_frame(fname)
        if vid is None:
            continue
        parts = root.split(os.sep)
        label, source = parts[-1], parts[-2]
        celeb_video_frames.setdefault((source, label, vid), []).append((fidx, os.path.join(root, fname)))

CELEB_FRAMES_PROCESSED = "/content/celeb_df_frames_processed"
processed_count, filled_count, empty_videos = 0, 0, 0

for (source, label, vid), frame_list in celeb_video_frames.items():
    frame_list.sort(key=lambda x: x[0])
    dest_dir = os.path.join(CELEB_FRAMES_PROCESSED, source, label)
    os.makedirs(dest_dir, exist_ok=True)
    last_valid_crop = None
    any_valid = False
    for fidx, src_path in frame_list:
        cropped = detect_and_crop_face(src_path)
        if cropped is not None:
            last_valid_crop = cropped
            any_valid = True
            processed_count += 1
        elif last_valid_crop is not None:
            cropped = last_valid_crop
            filled_count += 1
        else:
            continue
        cv2.imwrite(os.path.join(dest_dir, f"{vid}_f{fidx}.jpg"), cropped)
    if not any_valid:
        empty_videos += 1

print(f"Cropped: {processed_count}, filled: {filled_count}, no-face videos: {empty_videos}")

# 7. Build manifest + sequence dataset for new test source
import pandas as pd

celeb_records = []
for root, _, files in os.walk(CELEB_FRAMES_PROCESSED):
    for fname in files:
        if fname.endswith(".jpg"):
            full_path = os.path.join(root, fname)
            parts = full_path.split(os.sep)
            celeb_records.append({"image_path": full_path, "source_dataset": parts[-3], "label": parts[-2]})

celeb_manifest = pd.DataFrame(celeb_records)
print(f"Total frames: {len(celeb_manifest)}")
print(celeb_manifest.groupby("label").size())

celeb_test_ds = VideoSequenceDataset(celeb_manifest, val_seq_transform, max_seq_len=N_CONSECUTIVE)
celeb_test_loader = DataLoader(celeb_test_ds, batch_size=6, shuffle=False, collate_fn=collate_sequences, num_workers=2)
print(f"Unique test videos: {len(celeb_test_ds)}")

# 8. Run
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix

model.eval()
celeb_labels, celeb_preds, celeb_probs = get_seq_predictions(model, celeb_test_loader, device)

print("=== Celeb-DF (brand new, never-trained-on source) ===")
print(f"Accuracy: {accuracy_score(celeb_labels, celeb_preds):.4f}")
print(f"AUC: {roc_auc_score(celeb_labels, celeb_probs):.4f}")
print(confusion_matrix(celeb_labels, celeb_preds))

"""## 8. Improve augmentation"""

# Stronger augmentation
import albumentations as A
IMG_SIZE = 224
from albumentations.pytorch import ToTensorV2

train_transform_v2 = A.Compose([
    A.Resize(IMG_SIZE, IMG_SIZE),
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.4),
    A.ImageCompression(quality_range=(35, 100), p=0.6),
    A.GaussianBlur(blur_limit=(1, 5), p=0.3),
    A.ColorJitter(brightness=0.2, contrast=0.25, saturation=0.25, hue=0.1, p=0.4),
    A.Downscale(scale_range=(0.5, 0.9), p=0.3),
    A.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ToTensorV2(),
])

# val_seq_transform stays unchanged

from torch.utils.data import Dataset, DataLoader


class VideoSequenceDataset(Dataset):
    def __init__(self, manifest_df, transform, max_seq_len=15):
        df = manifest_df.copy()
        parsed = df["image_path"].apply(lambda p: extract_video_id_and_frame(os.path.basename(p)))
        df["video_id"] = parsed.apply(lambda x: x[0])
        df["frame_idx"] = parsed.apply(lambda x: x[1])
        df = df.dropna(subset=["video_id", "frame_idx"])
        self.groups = df.sort_values("frame_idx").groupby("video_id")
        self.video_ids = list(self.groups.groups.keys())
        self.transform = transform
        self.max_seq_len = max_seq_len
        self.label_map = {"real": 0, "fake": 1}

    def __len__(self):
        return len(self.video_ids)

    def __getitem__(self, idx):
        vid = self.video_ids[idx]
        rows = self.groups.get_group(vid).head(self.max_seq_len)
        frames = []
        for _, row in rows.iterrows():
            img = np.array(Image.open(row["image_path"]).convert("RGB"))
            img = self.transform(image=img)["image"]
            frames.append(img)
        seq = torch.stack(frames)
        label = self.label_map[rows.iloc[0]["label"]]
        return seq, seq.shape[0], label

import os
import pandas as pd

SPLITS_DIR = "/content/drive/MyDrive/Video Spoof/data/video"
train_df = pd.read_csv(os.path.join(SPLITS_DIR, "split_train_temporal.csv"))
val_df = pd.read_csv(os.path.join(SPLITS_DIR, "split_val_temporal.csv"))
final_test_set = pd.read_csv(os.path.join(SPLITS_DIR, "split_test_heldout_temporal.csv"))

def collate_sequences(batch):
    seqs, lengths, labels = zip(*batch)
    max_len = max(lengths)
    padded = torch.zeros(len(seqs), max_len, *seqs[0].shape[1:])
    for i, s in enumerate(seqs):
        padded[i, :s.shape[0]] = s
    return padded, torch.tensor(lengths), torch.tensor(labels)

import re
BATCH_SIZE = 6


train_seq_ds_v2 = VideoSequenceDataset(train_df, train_transform_v2, max_seq_len=N_CONSECUTIVE)
train_seq_loader_v2 = DataLoader(train_seq_ds_v2, batch_size=BATCH_SIZE, shuffle=True,
                                    collate_fn=collate_sequences, num_workers=2)

print(f"Train videos (v2 augmentation): {len(train_seq_ds_v2)}")

CHECKPOINT_DIR = "/content/drive/MyDrive/Video Spoof/checkpoints/video"

existing_ckpt = os.path.join(CHECKPOINT_DIR, "best_model_v2.pt")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = CBAM_GRU_DeepfakeDetector(
    backbone_checkpoint=existing_ckpt if os.path.exists(existing_ckpt) else None
).to(device)
print("Model ready.")

TEMPORAL_CHECKPOINT_DIR = "/content/drive/MyDrive/Video Spoof/checkpoints/video_temporal_v2"
def train_one_epoch_seq(model, loader, criterion, optimizer, device):
    model.train()
    running_loss, correct, total = 0.0, 0, 0
    for seqs, lengths, labels in loader:
        seqs, labels = seqs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(seqs, lengths)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item() * seqs.size(0)
        correct += (outputs.argmax(1) == labels).sum().item()
        total += labels.size(0)
    return running_loss / total, correct / total

# Load your current best checkpoint and continue fine-tuning with the new augmentation
model.load_state_dict(torch.load(os.path.join(TEMPORAL_CHECKPOINT_DIR, "best_cbam_gru_consecutive.pt")))

optimizer = torch.optim.Adam(model.parameters(), lr=3e-5)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="min", factor=0.5, patience=2)

EPOCHS = 8
best_val_acc = 0.0
history_v2 = {"train_loss": [], "train_acc": [], "val_loss": [], "val_acc": []}

for epoch in range(EPOCHS):
    train_loss, train_acc = train_one_epoch_seq(model, train_seq_loader_v2, criterion, optimizer, device)
    val_loss, val_acc = validate_seq(model, val_seq_loader, criterion, device)
    scheduler.step(val_loss)

    history_v2["train_loss"].append(train_loss); history_v2["train_acc"].append(train_acc)
    history_v2["val_loss"].append(val_loss); history_v2["val_acc"].append(val_acc)

    print(f"Epoch {epoch+1}/{EPOCHS} | Train acc: {train_acc:.4f} | Val loss: {val_loss:.4f}, acc: {val_acc:.4f}")

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), os.path.join(TEMPORAL_CHECKPOINT_DIR, "best_cbam_gru_augmented.pt"))
        print("  Saved.")

print(f"\nBest val acc: {best_val_acc:.4f}")

# Re-test on Celeb-DF
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix


model.load_state_dict(torch.load(os.path.join(TEMPORAL_CHECKPOINT_DIR, "best_cbam_gru_augmented.pt"), map_location=torch.device('cpu')))
model.eval()

celeb_labels_v2, celeb_preds_v2, celeb_probs_v2 = get_seq_predictions(model, celeb_test_loader, device)
print(f"Celeb-DF (before) — Acc: 0.70, AUC: 0.78")
print(f"Celeb-DF (after augmentation) — Acc: {accuracy_score(celeb_labels_v2, celeb_preds_v2):.4f}, "
      f"AUC: {roc_auc_score(celeb_labels_v2, celeb_probs_v2):.4f}")

from sklearn.metrics import confusion_matrix
cm_v2 = confusion_matrix(celeb_labels_v2, celeb_preds_v2)
print(cm_v2)

tn, fp, fn, tp = cm_v2.ravel()
print(f"Real accuracy: {tn/(tn+fp):.4f}")
print(f"Fake accuracy: {tp/(tp+fn):.4f}")

# Quick threshold check on Celeb-DF itself (exploratory only — for diagnosis, not
# for reporting as your "true" number, since tuning ON the test set would be circular)
from sklearn.metrics import roc_curve

fpr, tpr, thresholds = roc_curve(celeb_labels_v2, celeb_probs_v2)
j_scores = tpr - fpr
best_idx = np.argmax(j_scores)
print(f"Best threshold if tuned on Celeb-DF itself (exploratory): {thresholds[best_idx]:.3f}")
print(f"Would give — TPR: {tpr[best_idx]:.3f}, FPR: {fpr[best_idx]:.3f}")

"""## Live Test"""

# Live test

import cv2
import numpy as np
import torch

# if new:
# model (loaded with best_cbam_gru_augmented.pt), device, detector, val_seq_transform, best_val_threshold

def extract_consecutive_crops(video_path, detector, n_consecutive=15, start_offset_ratio=0.1):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        return []

    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    if total_frames <= 0:
        cap.release()
        return []

    start_frame = int(total_frames * start_offset_ratio)
    start_frame = min(start_frame, max(0, total_frames - n_consecutive))
    cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame)

    crops = []
    last_valid = None
    saved = 0
    while saved < n_consecutive:
        ret, frame = cap.read()
        if not ret:
            break
        h, w = frame.shape[:2]
        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        import mediapipe as mp
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=rgb)
        result = detector.detect(mp_image)

        cropped = None
        if result.detections:
            best = max(result.detections, key=lambda d: d.categories[0].score)
            bbox = best.bounding_box
            margin = 0.2
            x1 = max(0, int(bbox.origin_x - bbox.width * margin))
            y1 = max(0, int(bbox.origin_y - bbox.height * margin))
            x2 = min(w, int(bbox.origin_x + bbox.width * (1 + margin)))
            y2 = min(h, int(bbox.origin_y + bbox.height * (1 + margin)))
            face = frame[y1:y2, x1:x2]
            if face.size > 0:
                cropped = cv2.resize(face, (224, 224))

        if cropped is not None:
            last_valid = cropped
            crops.append(cropped)
            saved += 1
        elif last_valid is not None:
            crops.append(last_valid)
            saved += 1

    cap.release()
    return crops


def predict_video_final(video_path, model, detector, transform, device, threshold):
    crops = extract_consecutive_crops(video_path, detector)
    if len(crops) == 0:
        return None, "No face detected — cannot assess"

    frames = [transform(image=cv2.cvtColor(c, cv2.COLOR_BGR2RGB))["image"] for c in crops]
    seq = torch.stack(frames).unsqueeze(0).to(device)
    length = torch.tensor([len(frames)])

    model.eval()
    with torch.no_grad():
        outputs = model(seq, length)
        prob = torch.softmax(outputs, dim=1)[0, 1].item()

    verdict = "LIKELY FAKE" if prob >= threshold else "LIKELY REAL"
    return prob, verdict

# Recompute best_val_threshold
from sklearn.metrics import roc_curve
import numpy as np

# Make sure model is loaded
model.load_state_dict(torch.load(
    os.path.join(TEMPORAL_CHECKPOINT_DIR, "best_cbam_gru_augmented.pt"), map_location=device
))
model.eval()

# Get predictions on val set
val_labels_aug, val_preds_aug, val_probs_aug = get_seq_predictions(model, val_seq_loader, device)

# Youden's J
fpr_val, tpr_val, thresh_val = roc_curve(val_labels_aug, val_probs_aug)
j_scores_val = tpr_val - fpr_val
best_val_threshold = thresh_val[np.argmax(j_scores_val)]

print(f"best_val_threshold: {best_val_threshold:.4f}")

# Run on all videos in your live_test folder
import os

LIVE_TEST_ROOT = "/content/drive/MyDrive/Video Spoof/data/live_test"

results = []
for label_folder in ["real", "fake", "unknown"]:
    folder_path = os.path.join(LIVE_TEST_ROOT, label_folder)
    if not os.path.exists(folder_path):
        continue
    for fname in os.listdir(folder_path):
        if not fname.endswith((".mp4", ".mov", ".avi")):
            continue
        video_path = os.path.join(folder_path, fname)
        prob, verdict = predict_video_final(video_path, model, detector, val_seq_transform, device, best_val_threshold)

        if prob is None:
            print(f"{fname}: {verdict}")
            continue

        results.append({
            "filename": fname,
            "ground_truth": label_folder if label_folder != "unknown" else None,
            "predicted": "fake" if verdict == "LIKELY FAKE" else "real",
            "fake_probability": prob,
        })
        print(f"{fname}: {verdict} (prob={prob:.3f}, threshold={best_val_threshold:.3f}, ground_truth={label_folder})")

import pandas as pd
results_df = pd.DataFrame(results)
results_df.to_csv(os.path.join(LIVE_TEST_ROOT, "live_test_results_v2.csv"), index=False)
print(f"\nSaved to {LIVE_TEST_ROOT}/live_test_results_v2.csv")

# Accuracy on labeled videos
labeled = results_df[results_df["ground_truth"].notna()]
if len(labeled) > 0:
    correct = (labeled["ground_truth"] == labeled["predicted"]).sum()
    print(f"Accuracy: {correct}/{len(labeled)} = {correct/len(labeled):.3f}")
    print(labeled[["filename", "ground_truth", "predicted", "fake_probability"]])